# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: marys-purple-light.toml
  theme_night: marys-purple-light.toml
  font: mary-serif
  font_size: S
  #favicon: favicon.ico

# SEO

#favicon: favicon.ico

marketing:
  #favicon: favicon.ico
  seo:
    site_type: Person
    local_business_type: 'Mary Letey'
    org_name: 'Mary Letey'
    description: 'Mary Leteys personal website - currently Applied Maths student at Harvard.'
    # description: 'Mary Letey Homepage Physics Mathematics Machine Learning Mary Letey'
     #twitter: 'wowchemy'
     
# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Mary Letey'
  icon: otter
  icon_pack: fas

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  #favicon: favicon.ico
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: square
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
