# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  #theme_day: marys-theme
  theme_night: marys-purple
  font: mary-serif
  font_color: rgba(246, 5, 239, 1)
  font_size: M

# SEO

 #marketing:
   #seo:
    # site_type: Person
     #local_business_type: 'Mary Letey'
    # org_name: 'Mary Letey'
    # description: 'Mary Letey Homepage Physics Mathematics Machine Learning Mary Letey'
     #twitter: 'wowchemy'
     
# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Mary Letey'
  icon: otter
  icon_pack: fas

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    #theme_light: github-light
    #theme_night: marys-theme
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: square
  assets:
    favicon: /assets/favicon.ico
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: true
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

params:
  favicon: /favicon.ico

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
